[GLOBAL]
pants_version = "1.29.0rc0"
v1 =  true  # keep using the v1 as well
v2 = true  # Enable the v2 execution engine.
dynamic_ui = true
enable_pantsd = true  # Enable the Pants daemon for better performance.

pants_ignore_use_gitignore = false

backend_packages2.add = [
  'pants.backend.python',
  'pants.backend.python.lint.bandit',
  'pants.backend.python.lint.black',
  'pants.backend.python.lint.flake8',
  'pants.backend.python.lint.isort',
  'pants.backend.python.lint.pylint',
]

# List v2 plugins here. 
plugins2 = []

process_execution_local_parallelism = 1

[source]
root_patterns = [
  "/",
]

[pytest]
version = "pytest==5.4.3"
pytest_plugins.add = [
  # improve diffs when comparing objects in tests
  "pytest-icdiff==0.5",
  # add syntax highlighting for pytest output
  "pygments==2.6.1",
  # allow to use ipdb instead of pdb in debug mode
  "ipdb==0.13.2",
  "pytest-envvars",
]
